//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoryTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public categoryTB()
        {
            this.storeTB = new HashSet<storeTB>();
        }
    
        public int categoryID { get; set; }
        public string categoryName { get; set; }
        public Nullable<int> productID { get; set; }
    
        public virtual productsTB productsTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storeTB> storeTB { get; set; }
    }
}
