//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Automation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class marketDBEntities : DbContext
    {
        public marketDBEntities()
            : base("name=marketDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoryTB> categoryTB { get; set; }
        public virtual DbSet<productsTB> productsTB { get; set; }
        public virtual DbSet<storeTB> storeTB { get; set; }
        public virtual DbSet<supplierTB> supplierTB { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<userInformationTB> userInformationTB { get; set; }
        public virtual DbSet<userTB> userTB { get; set; }
    }
}
