//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class storeTB
    {
        public int storeID { get; set; }
        public string storeName { get; set; }
        public string storeAddress { get; set; }
        public Nullable<int> supplierID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> userID { get; set; }
    
        public virtual categoryTB categoryTB { get; set; }
        public virtual productsTB productsTB { get; set; }
        public virtual supplierTB supplierTB { get; set; }
        public virtual userTB userTB { get; set; }
    }
}
