//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplierTB()
        {
            this.storeTB = new HashSet<storeTB>();
        }
    
        public int supplierID { get; set; }
        public string supplierName { get; set; }
        public string supplierPassword { get; set; }
        public string supplierRName { get; set; }
        public string supplierSurname { get; set; }
        public string supplierEmail { get; set; }
        public string supplierPNumber { get; set; }
        public string userCity { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storeTB> storeTB { get; set; }
    }
}
