//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userTB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public userTB()
        {
            this.storeTB = new HashSet<storeTB>();
            this.userInformationTB = new HashSet<userInformationTB>();
        }
    
        public int userID { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public string userAuthority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<storeTB> storeTB { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<userInformationTB> userInformationTB { get; set; }
    }
}
