//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Automation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class userInformationTB
    {
        public int userInformationID { get; set; }
        public Nullable<int> userID { get; set; }
        public string userIdentity { get; set; }
        public string userRealName { get; set; }
        public string userSurname { get; set; }
        public System.DateTime userBirthdate { get; set; }
        public string userMotherName { get; set; }
        public string userFatherName { get; set; }
        public string userPhone { get; set; }
        public string userEmail { get; set; }
        public string userCity { get; set; }
        public bool userGender { get; set; }
    
        public virtual userTB userTB { get; set; }
    }
}
